### ISSUE TITLE
Komendy są case sensitive

### ISSUE THREAD

**Issue by kucyk** [kucyk/BlabPrezent#9]
Gdy np. ktoś wpiszę "Dodaj" bot już nie zrozumie.

Przykład w kodzie tutaj:
https://github.com/kucyk/BlabPrezent/blob/master/commandhandlers/addinghandler.py#L16

Dość istotne, bo na urządzeniach mobilnych domyślnie autokorekta podpowiada pierwszy wyraz zdania wielką literą. Przejrzeć inne komendy.

**Comment by rmikke** [comment]
Już powinien rozumieć, masz PR.
